version: '3.9'
services:
  api:
    build: ./apps/api
    image: image_api
    restart: always
    container_name: api
    environment:
      NODE_ENV: test
    ports:
      - 3000:3000
    depends_on:
      - db
      - activity-service
      - swagger

  activity-service:
    build: ./apps/activityService
    image: image_activity_service
    restart: always
    container_name: activity_service
    environment:
      NODE_ENV: test
    ports:
      - 3001:3001
    depends_on:
      - db

  swagger:
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile.swagger
    image: image_swagger
    restart: always
    container_name: swagger
    environment:
      BASE_URL: /api-docs
      SWAGGER_JSON: /api.json
    ports:
      - 8080:8080


  db:
    build: ./db
    image: image_db
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: iCommerce
